### ISSUE TITLE
Bot non più funzionante

### ISSUE THREAD

**Issue by Alessandro1996** [TopoDiFogna/poli_telegram_bot#5]
Salve,
ho utilizzato questo bot per parecchio tempo, ma è quasi un mese che il bot non funziona più, riceve messaggi senza dare un riscontro.
 Potreste gentilmente spiegarmi perché non funziona più?

**Comment by TopoDiFogna** [comment]
Ciao! Ti consigliamo di provare [@university_staging_bot](t.me/university_staging_bot) , una nuova versione :)
